# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    weight: 10
    identifier: Home
  - name: About Me
    url: '#about'
    weight: 10
    parent: Home
  - name: Experience
    url: '#experience'
    weight: 20
    parent: Home
  - name: Honors & Awards
    url: '#accomplishments'
    weight: 30
    parent: Home
  - name: CV
    url: uploads/resume.pdf
    weight: 20
  - name: Research
    url: '#research-agenda'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Teaching
    url: '#teaching'
    weight: 60
  - name: Outreach
    url: '#outreach'
    weight: 70
  - name: Press
    url: '#press'
    weight: 80
  - name: Blog
    url: '#blog'
    weight: 90
  - name: Contact
    weight: 100
    identifier: Contact
  - name: Consulting
    url: '#consulting'
    weight: 10
    parent: Contact
  - name: Industry Collaboration
    url: '#industry-collaboration'
    weight: 20
    parent: Contact
  - name: Outreach Request
    url: '#outreach-request'
    weight: 30
    parent: Contact
  - name: Other
    url: '#other'
    weight: 40
    parent: Contact
  
